version: "3.8"

services:
  app:
    container_name: nextjs-dev
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    command: npm run dev