version: "3.8"

services:
  app:
    container_name: nextjs-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always